# Generated by Django 2.2.5 on 2021-01-10 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20210110_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='amenity',
        ),
        migrations.RemoveField(
            model_name='room',
            name='fAcility',
        ),
        migrations.RemoveField(
            model_name='room',
            name='house_rule',
        ),
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='rooms.Amenity'),
        ),
        migrations.AddField(
            model_name='room',
            name='facilities',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='rooms.Facility'),
        ),
        migrations.AddField(
            model_name='room',
            name='house_rules',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='rooms.HouseRule'),
        ),
    ]
