# Generated by Django 2.2.5 on 2021-01-10 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20210110_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='geusts',
            new_name='guests',
        ),
    ]
